### ISSUE TITLE
mismatch between the model architecture in the checkpoint and the given tok pre-trained model.

### ISSUE THREAD

**Issue by zmqgeek** [LASER-UMASS/Passport#1]
python evaluate.py ours tok --path runs/tok/checkpoints/model_002.pth
The following error occurred when I evaluated using the given tok pretrained model:

Namespace(beam_width=20, bpe_merges=4096, case_insensitive_idents=False, config=None, constructor_vocab_file='./names/constructors-known-100.pickle', coq_projects='../coq_projects', cutoff_len=30, datapath='../data', debug=False, def_vocab_file='./names/names-known-200.pickle', depth_limit=50, embedding_dim=128, eval_id='tok', export_config=None, file=None, file_idx=None, filter=None, globals_file='./names/names.pickle', hammer_timeout=100, hidden_dim=128, ident_vec_size=32, include_constructor_names=True, include_defs=True, include_locals=True, include_paths=True, include_prev_tactics=True, include_serapi=True, include_unks=False, lens_norm=0.5, load_subwords='names/subwords.json', local_vocab_file='./names/locals-known-200.pickle', locals_file='./names/locals.pickle', max_ident_chunks=8, max_num_tactics=300, merge_vocab=False, merged_file='./names/merged.pickle', method='ours', num_tactic_candidates=20, num_tactics=15025, output_dir='evaluation', path='runs/tok/checkpoints/model_002.pth', path_vocab_file='./names/paths-known-200.pickle', paths_file='./names/paths.pickle', proj_idx=None, projs_split='../projs_split.json', proof=None, save_subwords='names/subwords.json', seed=0, size_limit=50, split='test', symbol_dim=128, tac_embedding=256, tac_grammar='tactics.ebnf', tac_layers=1, tac_vocab_file='token_vocab.pickle', teacher_forcing=1.0, term_embedding_dim=128, timeout=600, use_locals_file=True)
WARNING: using CPU
Building vocab:
100% (4096 of 4096) |##################################################################################################| Elapsed Time: 0:04:04 Time:  0:04:04
loading model checkpoint from runs/tok/checkpoints/model_002.pth..
Traceback (most recent call last):
  File "evaluate.py", line 90, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/work/home/ack31c9mp7/perl5/bin/anaconda3/envs/passport/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Prover:
        size mismatch for term_encoder.input_gate.W: copying a param with shape torch.Size([128, 1069]) from checkpoint, the shape in current model is torch.Size([128, 1090]).
        size mismatch for term_encoder.forget_gates.W_if: copying a param with shape torch.Size([128, 941]) from checkpoint, the shape in current model is torch.Size([128, 962]).
        size mismatch for term_encoder.output_gate.W: copying a param with shape torch.Size([128, 1069]) from checkpoint, the shape in current model is torch.Size([128, 1090]).
        size mismatch for term_encoder.update_cell.W: copying a param with shape torch.Size([128, 1069]) from checkpoint, the shape in current model is torch.Size([128, 1090]).
        size mismatch for term_encoder.name_encoder.weight_ih_l0: copying a param with shape torch.Size([32, 4164]) from checkpoint, the shape in current model is torch.Size([32, 4167]).

Can you help me solve it?

**Comment by zmqgeek** [comment]
Although I added the --no-locals-file parameter afterwards, this error still persists. The difference is that the last line of the error output regarding the mismatch is gone, but the earlier lines of the error regarding the mismatch still remain.

Namespace(beam_width=20, bpe_merges=4096, case_insensitive_idents=False, config=None, constructor_vocab_file='./names/constructors-known-100.pickle', coq_projects='../coq_projects', cutoff_len=30, datapath='../data', debug=False, def_vocab_file='./names/names-known-200.pickle', depth_limit=50, embedding_dim=128, eval_id='tok', export_config=None, file=None, file_idx=None, filter=None, globals_file='./names/names.pickle', hammer_timeout=100, hidden_dim=128, ident_vec_size=32, include_constructor_names=True, include_defs=True, include_locals=True, include_paths=True, include_prev_tactics=True, include_serapi=True, include_unks=False, lens_norm=0.5, load_subwords='names/subwords.json', local_vocab_file='./names/locals-known-200.pickle', locals_file='./names/locals.pickle', max_ident_chunks=8, max_num_tactics=300, merge_vocab=False, merged_file='./names/merged.pickle', method='ours', num_tactic_candidates=20, num_tactics=15025, output_dir='evaluation', path='runs/tok/checkpoints/model_002.pth', path_vocab_file='./names/paths-known-200.pickle', paths_file='./names/paths.pickle', proj_idx=None, projs_split='../projs_split.json', proof=None, save_subwords='names/subwords.json', seed=0, size_limit=50, split='test', symbol_dim=128, tac_embedding=256, tac_grammar='tactics.ebnf', tac_layers=1, tac_vocab_file='token_vocab.pickle', teacher_forcing=1.0, term_embedding_dim=128, timeout=600, use_locals_file=False)
WARNING: using CPU
Warning: Loaded subwords don't match the occurances we loaded, regenerating
Building vocab:
100% (4096 of 4096) |##################################################################################################| Elapsed Time: 0:03:27 Time:  0:03:27
loading model checkpoint from runs/tok/checkpoints/model_002.pth..
Traceback (most recent call last):
  File "evaluate.py", line 90, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/work/home/ack31c9mp7/perl5/bin/anaconda3/envs/passport/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Prover:
        size mismatch for term_encoder.input_gate.W: copying a param with shape torch.Size([128, 1069]) from checkpoint, the shape in current model is torch.Size([128, 1090]).
        size mismatch for term_encoder.forget_gates.W_if: copying a param with shape torch.Size([128, 941]) from checkpoint, the shape in current model is torch.Size([128, 962]).
        size mismatch for term_encoder.output_gate.W: copying a param with shape torch.Size([128, 1069]) from checkpoint, the shape in current model is torch.Size([128, 1090]).
        size mismatch for term_encoder.update_cell.W: copying a param with shape torch.Size([128, 1069]) from checkpoint, the shape in current model is torch.Size([128, 1090]).

**Comment by zmqgeek** [comment]
I solved the issue by modifying the following parameters.
-    parser.add_argument('--path_vocab_file', type=str, default='./names/paths-known-200.pickle')
-    parser.add_argument('--constructor_vocab_file', type=str, default='./names/constructors-known-100.pickle')
+    parser.add_argument('--path_vocab_file', type=str, default='./names/paths-known-220.pickle')
+    parser.add_argument('--constructor_vocab_file', type=str, default='./names/constructors-known-200.pickle')
